axis_linear: 1.0  # Left thumb stick vertical
scale_linear: 0.01
scale_linear_turbo: 1.0

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.3

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
