bbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------    
  base2right_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2right_top_leg

  base2left_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2left_top_leg
  
  right_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: right_top_leg2bottom_leg

  left_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: left_top_leg2bottom_leg

  # LQR Controller ---------------------------------------    
  mobile_base_controller:
    type: lqr_controller/LQRController
    left_wheel: left_bottom_leg2wheel
    right_wheel: right_bottom_leg2wheel
    control_period: -1          # seconds = 80 Hz
    wheel_separation: 0.1431    # meters
    wheel_radius: 0.05          # meters
    balance_angle_offset: 0.17
    imu_topic: /bbot/imu/data_filtered
    # The first and second line of the K gain matrix
    K_l1: [-12919.3411918064, -3960.89635807413, -597.282038109003, -29349.5532847772, 0.257863532914322, 0.111520895110095, -2.14099392008506e-38, 3.71571600043629e-17]
    K_l2: [-12919.3411918063, -3960.89635807414,  597.282038109007, -29349.5532847772, 0.111520895110095, 0.257863532914323, -8.48211735414508e-39, 1.47207980717306e-17]