bbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------    
  base2right_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2right_top_leg

  base2left_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2left_top_leg
  
  right_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: right_top_leg2bottom_leg

  left_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: left_top_leg2bottom_leg

  # LQR Controller ---------------------------------------    
  mobile_base_controller:
    type: lqr_controller/LQRController
    left_wheel: left_bottom_leg2wheel
    right_wheel: right_bottom_leg2wheel
    control_period: -1          # seconds = 80 Hz
    wheel_separation: 0.1431    # meters
    wheel_radius: 0.05          # meters
    balance_angle_offset: 0.168
    imu_topic: /bbot/imu/data_filtered
    # The first and second line of the K gain matrix
    K_l1: [-10060.1716643338,  -2676.5584372318, -40.3751151332752, -23543.2490667998,  0.102215936175319, 0.0924884299086031, -1.11533123841518e-17, -3.28779478711571e-18]
    K_l2: [-10060.1716643338, -2676.55843723181,  40.3751151332766, -23543.2490667999, 0.0924884299086032,   0.10221593617532, -1.11533123841518e-17,   3.3748477567755e-18]