bbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------    
       
  base2right_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2right_top_leg

  base2left_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2left_top_leg
  
  right_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: right_top_leg2bottom_leg

  left_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: left_top_leg2bottom_leg

  # mobile_base_controller:
  #   type: my_controller/MyPositionController
  #   joint: left_bottom_leg2wheel
  #   gain: 0.1
    
  mobile_base_controller:
    type: lqr_controller/LQRController
    left_wheel: left_bottom_leg2wheel
    right_wheel: right_bottom_leg2wheel
    control_period: -1 # seconds = 25 Hz
    wheel_separation: 0.1431  # meters
    wheel_radius: 0.05        # meters
    balance_angle_offset: 0.16
    imu_topic: /bbot/imu/data_filtered
    # The first and second line of the K gain matrix
    K_l1: [-0.359816139587012,  -0.16899712716524, -0.062273242637461, -1.04054845575376, 0.00552059416223505,  0.0178652255170376]
    K_l2: [-0.359816139587049, -0.168997127165247,  0.062273242637461, -1.04054845575384, 0.00552059416223684, -0.0178652255170376]