bbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------    
  base2right_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2right_top_leg

  base2left_top_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: base2left_top_leg
  
  right_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: right_top_leg2bottom_leg

  left_top_leg2bottom_leg_position_controller:
    type: position_controllers/JointPositionController
    joint: left_top_leg2bottom_leg

  # LQR Controller ---------------------------------------    
  mobile_base_controller:
    type: lqr_controller/LQRController
    left_wheel: left_bottom_leg2wheel
    right_wheel: right_bottom_leg2wheel
    control_period: -1          # seconds = 80 Hz
    wheel_separation: 0.1431    # meters
    wheel_radius: 0.05          # meters
    balance_angle_offset: 0.17
    imu_topic: /bbot/imu/data_filtered
    # The first and second line of the K gain matrix
    K_l1: [-10018.0947309438, -2652.11124154826, -37.2227737600539, -23420.1654462429,  0.100520789055982, 0.0918054885246288, 0.718141332538351,  0.787121116536764]
    K_l2: [-10018.0947309438, -2652.11124154825,   37.222773760054, -23420.1654462428, 0.0918054885246287,  0.100520789055981, 0.718141332538329, -0.787121116536779]